### ISSUE TITLE
[Feature Request] extract the getSrcSet methods to Job classes that can be overridden in the config

### ISSUE THREAD

**Issue by pryley** [moodley-interactive/statamic-responsive-image#2]
If you extracted the methods used to generate the image sizes into Job classes, and defined the job class in the config, this would allow us to easily extend the add-on to provide support for other Image Optimization Solutions (i.e. ImageKit).

You can see how the Spatie Responsive Images add-on does this here:

https://github.com/spatie/statamic-responsive-images/blob/master/config/responsive-images.php
https://github.com/spatie/statamic-responsive-images/tree/master/src/Jobs

For example, here is an ImageKit Job class I created for the Spatie add-on: 

https://gist.github.com/pryley/277b4ab275cd538168fb759471ab7e2c

**Comment by goellner** [comment]
That sounds good and we will implement that as soon as we have time. Could take a few week though. We would be open to a PR too, if you would like to contribute.

**Comment by pryley** [comment]
Hi, sorry for the late reply. However, I ended up using a different solution for my project.
